export enum BranchConfigKey {
  MAX_DISTANCE_DELIVERY = 'MAX_DISTANCE_DELIVERY',
  DELIVERY_FEE_PER_KM = 'DELIVERY_FEE_PER_KM', // PER KM
  WIFI_NAME = 'WIFI_NAME',
  WIFI_PASSWORD = 'WIFI_PASSWORD',
}
